### ISSUE TITLE
Cannot find 'AKMIDITrackView' in scope (In SwiftUI)

### ISSUE THREAD

**Issue by kjetilge** [AudioKit/MIDITrackView#1]
I'm trying to use AKMIDITrackView in Swiftui but AKMIDITrackView is not available. I get the error: Cannot find 'AKMIDITrackView' in scope. I've added AudioKit as a package dependency.

My code:

```
import SwiftUI
import AudioKit
struct ContentView: View {
    var body: some View {
        AKMIDITrackView(frame: CGRect(frame: CGRect(x:0, y:0, width:1000, height:300)))
            .swiftUIView(layout: .intrinsic)
    }
}
```

Also I can not find any documentation or code with a name containing "AKMIDITrackView" any where on the internet. Please help.

**Comment by emurray2** [comment]
The documentation can be found here: [https://github.com/AudioKit/AudioKitUI/wiki/MIDITrackView](https://github.com/AudioKit/AudioKitUI/wiki/MIDITrackView)

**Comment by kjetilge** [comment]
Thanks. Fixed it now!
This works:
```
import SwiftUI
import AudioKit
import AudioKitUI
import SwiftUIKitView

struct ContentView: View {
    var body: some View {
        MIDITrackView(frame: CGRect(x:0, y:0, width:1000, height:300))
            .swiftUIView(layout: .intrinsic)
    }
}
```

**Comment by kjetilge** [comment]
Yes. Found it:
```
    public convenience init(frame: CGRect, midiFile: URL!,
                            trackNumber: Int,
                            sampler: MIDISampler,
                            sequencer: AppleSequencer)
```

But I get: Extra argument 'midiFile' in call when I try this: 

```
        MIDITrackView(frame: CGRect(x:0, y:0, width:1000, height:300), midiFile: 'blues-drum-track')
            .swiftUIView(layout: .intrinsic)
```

**Comment by emurray2** [comment]
Interesting... It seems that `midiFile` is expected to be of type `URL!`. Try using `URL` instead of `String` as the parameter value type.

**Comment by kjetilge** [comment]
Hm. It didn't seem to help:
```
        MIDITrackView(frame: CGRect(x:0, y:0, width:1000, height:300), midiFile: URL(string: "blues-drum-track"))
            .swiftUIView(layout: .intrinsic)

```
Also I get the same error when trying this:
```
        MIDITrackView(frame: CGRect(x:0, y:0, width:1000, height:300), trackNumber: 10)
            .swiftUIView(layout: .intrinsic)
```

**Comment by kjetilge** [comment]
Wow! That's a great idea! Looking forward to try it 😊

**Comment by emurray2** [comment]
Just a warning, it may take me a couple days or so since I'm in school and cramming for a test, but I will try to finish it ASAP. In the meantime, please feel free to keep exploring with the code you have and try to get it working. Let me know if you do :)!

**Comment by emurray2** [comment]
I didn't want to keep you waiting, so I tried to come up with a quick fix. I believe to resolve the error you described above, you need to fill in all of the parameters in the `MIDITrackView`'s initializer like this:
```
//
//  ContentView.swift
//  MIDITrackTest
//
//  Created by Evan Murray on 10/17/21.
//

import SwiftUI
import AudioKitUI
import SwiftUIKitView
import AudioKitEX
import AudioKit

struct ContentView: View {
    let sampler = MIDISampler()
    let sequencer = AppleSequencer()
    var body: some View {
        Text("Hello, world!")
            .padding()
        MIDITrackView(frame: CGRect(x: 0, y: 0, width: 400, height: 100), midiFile: Bundle.main.url(forResource: "LVB_Sonate_02no1_1", withExtension: "mid")!, trackNumber: 0, sampler: sampler, sequencer: sequencer)
            .swiftUIView(layout: .intrinsic)
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}
```
The MIDI file I used can be found here: [https://www.mutopiaproject.org/cgibin/make-table.cgi?collection=beetson&preview=1](https://www.mutopiaproject.org/cgibin/make-table.cgi?collection=beetson&preview=1)

This is what the app looked like:
![IMG_6CF513BDAF3F-1](https://user-images.githubusercontent.com/15041342/137650613-1701eeae-43b0-49f0-b8f7-905fd79f3728.jpeg)
:

Now the challenge will be figuring out how to play the MIDI track. I know there's a `play()` method, but I'm working on figuring out how to use it in swift ui.

**Comment by aure** [comment]
Do we even need this repo anymore then?

**Comment by emurray2** [comment]
> Do we even need this repo anymore then?

No, it would probably be better to move this inside the Cookbook.

**Comment by kjetilge** [comment]
> I didn't want to keep you waiting, so I tried to come up with a quick fix. I believe to resolve the error you described above, you need to fill in all of the parameters in the `MIDITrackView`'s initializer like this:
> 
> ```
> //
> //  ContentView.swift
> //  MIDITrackTest
> //
> //  Created by Evan Murray on 10/17/21.
> //
> 
> import SwiftUI
> import AudioKitUI
> import SwiftUIKitView
> import AudioKitEX
> import AudioKit
> 
> struct ContentView: View {
>     let sampler = MIDISampler()
>     let sequencer = AppleSequencer()
>     var body: some View {
>         Text("Hello, world!")
>             .padding()
>         MIDITrackView(frame: CGRect(x: 0, y: 0, width: 400, height: 100), midiFile: Bundle.main.url(forResource: "LVB_Sonate_02no1_1", withExtension: "mid")!, trackNumber: 0, sampler: sampler, sequencer: sequencer)
>             .swiftUIView(layout: .intrinsic)
>     }
> }
> 
> struct ContentView_Previews: PreviewProvider {
>     static var previews: some View {
>         ContentView()
>     }
> }
> ```
> 
> The MIDI file I used can be found here: https://www.mutopiaproject.org/cgibin/make-table.cgi?collection=beetson&preview=1
> 
> This is what the app looked like: ![IMG_6CF513BDAF3F-1](https://user-images.githubusercontent.com/15041342/137650613-1701eeae-43b0-49f0-b8f7-905fd79f3728.jpeg) :
> 
> Now the challenge will be figuring out how to play the MIDI track. I know there's a `play()` method, but I'm working on figuring out how to use it in swift ui.

Thanks for this. It finally got me up and running!

It seems to only work with midi type 0 though. Also it does not show meta events like markers and text and so on. I think this view must be used togheter with Sequencer in order for anything to be played. I'm experimenting with it now.

**Comment by emurray2** [comment]
@kjetilge I made `MIDITrackView` compatible with SwiftUI in AudioKit/AudioKitUI#40. Once that's merged, I'll add an example to AudioKit/Cookbook which you can look at. It's much easier to use now, and no need for the SwiftUI `UIView` wrapper anymore 😃!

**Comment by emurray2** [comment]
Alright, the new `MIDITrackView` is Cookbook! Should be ready by the next release, but you can also checkout the `develop` branch to experiment with it in the meantime :) !

**Comment by aure** [comment]
Should this repoo even exist anymore?

**Comment by emurray2** [comment]
> Should this repo even exist anymore?

Nope, I think it's safe to delete it 🙂
